# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: meme-police
variablesResolutionMode: 20210326

useDotenv: true
# app and org for use with dashboard.serverless.com
app: meme-police
org: hokedo12

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-python-requirements
  - serverless-lift

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource:
            - "Fn::GetAtt": [picturesTable, Arn]
  environment:
    PICTURES_TABLE_NAME: meme-police-${sls:stage}-${env:PICTURES_TABLE_NAME}

functions:
  check-meme:
    handler: handler.check_telegram_webhook_handler
    timeout: 3
    environment:
      HARDCODED_USER: ${env:HARDCODED_USER}
      HARDCODED_PASSWORD: ${env:HARDCODED_PASSWORD}
      CHECK_MEME_QUEUE_URL: ${construct:check-meme-queue.queueUrl}
    layers:
      - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-Pillow:15
    events:
      - http:
          path: check-meme
          method: post


resources: # CloudFormation template syntax from here on.
  Resources:
    picturesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PICTURES_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: stripped_url
            AttributeType: S
        KeySchema:
          - AttributeName: stripped_url
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

constructs:
  check-meme-queue:
    type: queue
    worker:
      handler: handler.check_duplicate_meme_handler
      timeout: 200
      layers:
        - arn:aws:lambda:eu-central-1:770693421928:layer:Klayers-python38-Pillow:15

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false # avoid some ELF alignment issues
    slimPatternsAppendDefaults: false
    slimPatterns:
      # Won't work with noDeploy since
      # dependencies will go back
      - PIL/**
      - Pillow*/**
      # Exclude **/*.dist-info* may cause trouble
      - '**/*.py[c|o]'
      - '**/__pycache__*'
  dotenv:
    exclude:
      - PICTURES_TABLE_NAME